import js from "@eslint/js";
import eslintPluginPrettier from "eslint-plugin-prettier/recommended";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";

export default tseslint.config(
  {
    // These 4 route files are auto-generated by the @lovable.dev/mcp-js Vite plugin
    // on every build/dev run (each carries a "// AUTO-GENERATED ... do not edit"
    // banner) and are regenerated in a form that doesn't match this project's
    // Prettier config. Running eslint --fix on them isn't durable: the next
    // `npm run build` regenerates and un-formats them again. Excluding them from
    // lint respects the plugin's own "do not edit" ownership model instead of
    // fighting output it controls.
    ignores: ["src/routes/\\[.mcp\\]/**", "src/routes/\\[.well-known\\]/**", "src/routes/mcp.ts"],
  },
  {
    ignores: ["dist", ".output", ".vinxi"],
  },
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
    plugins: {
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "server-only",
              message:
                "TanStack Start does not use the Next.js `server-only` package. Rename the module to `*.server.ts` or mark it with `@tanstack/react-start/server-only`.",
            },
          ],
        },
      ],
      "react-refresh/only-export-components": ["warn", { allowConstantExport: true }],
      "@typescript-eslint/no-unused-vars": "off",
    },
  },
  eslintPluginPrettier,
);
