"""
face_engine/datatypes.py

Data transfer objects used across the face engine.
All cross-module data is passed as typed dataclasses — never raw dicts.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime

import numpy as np

from face_engine.detector import FaceBox


@dataclass
class RecognitionResult:
    """Result of recognising one face in a frame."""
    employee_id: str | None          # None = Unknown
    employee_name: str | None
    similarity_score: float
    metric_used: str                 # "cosine" or "l2"
    is_match: bool
    face_box: FaceBox
    rejection_reason: str | None     # "below_threshold" / "no_face" / etc.
    inference_time_ms: float


@dataclass
class EnrollmentResult:
    """Result of attempting to enroll an employee."""
    success: bool
    employee_id: str
    accepted_image_count: int
    rejected_image_count: int
    rejection_details: list[dict]    # [{image_index, reason, value, threshold}]
    failure_reason: str | None       # Set when success=False
    embedding: np.ndarray | None     # Set when success=True; caller saves this


@dataclass
class AttendanceRecord:
    """One attendance event written to the database."""
    id: str                          # UUID generated by DB
    employee_id: str
    camera_id: str
    event_type: str                  # "check_in" or "check_out"
    similarity_score: float
    metric_used: str
    snapshot_path: str | None
    marked_at: datetime
    liveness_checked: bool           # Always log — audit trail
