"""
database/models.py

SQLAlchemy ORM models.

TABLE: employees
    - id: employee_id string (PK, e.g. "EMP001")
    - name: display name
    - department: optional department label
    - embedding: float32 embedding stored as BYTEA (512 bytes = 128 × 4)
    - enrolled_at: UTC timestamp
    - is_active: soft-delete flag — never hard-delete enrolled employees
                 (preserves audit trail)

TABLE: attendance_events
    - id: UUID PK (generated by DB via gen_random_uuid())
    - employee_id: FK → employees.id ON DELETE RESTRICT
    - camera_id: string identifier for the camera source
    - event_type: "check_in" or "check_out"
    - similarity_score: float — the cosine/l2 score at time of match
    - metric_used: "cosine" or "l2"
    - snapshot_path: path to the saved image (nullable)
    - liveness_checked: bool — always recorded for audit trail
    - marked_at: UTC timestamp

DESIGN NOTES
------------
- Embedding stored as raw bytes (BYTEA), NOT as JSON / text.
  JSON encoding causes float precision loss that corrupts matching.
- No pgvector used here — linear scan is acceptable for ≤ 500 employees.
  Add pgvector index if employee count grows to 2000+.
- ON DELETE RESTRICT on employee_id FK prevents accidental employee deletion
  when attendance records exist.
"""

from __future__ import annotations

from datetime import datetime, timezone

from sqlalchemy import (
    Boolean,
    Column,
    DateTime,
    Float,
    ForeignKey,
    LargeBinary,
    String,
    Text,
    text,
)
from sqlalchemy.orm import DeclarativeBase, relationship


class Base(DeclarativeBase):
    pass


class Employee(Base):
    __tablename__ = "employees"

    id = Column(String(50), primary_key=True, nullable=False)
    name = Column(String(200), nullable=False)
    department = Column(String(100), nullable=True)

    # Raw float32 bytes — 128 × 4 = 512 bytes
    embedding = Column(LargeBinary, nullable=False)

    enrolled_at = Column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
    )
    is_active = Column(Boolean, nullable=False, default=True)

    # Relationship (back-populates for ORM convenience, not used in queries)
    attendance_events = relationship(
        "AttendanceEvent",
        back_populates="employee",
        lazy="select",
    )

    def __repr__(self) -> str:
        return f"<Employee id={self.id!r} name={self.name!r} active={self.is_active}>"


class AttendanceEvent(Base):
    __tablename__ = "attendance_events"

    # UUID generated by DB — works across PostgreSQL and SQLite (in tests)
    id = Column(String(36), primary_key=True, nullable=False)
    employee_id = Column(
        String(50),
        ForeignKey("employees.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
    )
    camera_id = Column(String(100), nullable=False)
    event_type = Column(String(20), nullable=False)          # "check_in" / "check_out"
    similarity_score = Column(Float, nullable=False)
    metric_used = Column(String(10), nullable=False)
    snapshot_path = Column(Text, nullable=True)
    liveness_checked = Column(Boolean, nullable=False, default=False)
    marked_at = Column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
    )

    employee = relationship("Employee", back_populates="attendance_events")

    def __repr__(self) -> str:
        return (
            f"<AttendanceEvent id={self.id!r} emp={self.employee_id!r} "
            f"type={self.event_type!r} at={self.marked_at}>"
        )
