/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as StatusRouteImport } from './routes/status'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAskRouteImport } from './routes/_authenticated/ask'
import { Route as AuthenticatedEmployeeRouteImport } from './routes/_authenticated/employee'
import { Route as AuthenticatedEnrollRouteImport } from './routes/_authenticated/enroll'
import { Route as AuthenticatedHelpRouteImport } from './routes/_authenticated/help'
import { Route as AuthenticatedParentRouteImport } from './routes/_authenticated/parent'
import { Route as AuthenticatedStudentRouteImport } from './routes/_authenticated/student'
import { Route as AuthenticatedTeacherRouteImport } from './routes/_authenticated/teacher'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AuthenticatedAttendSessionIdRouteImport } from './routes/_authenticated/attend.$sessionId'
import { Route as AuthSsoCallbackRouteImport } from './routes/auth.sso.callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAskRoute = AuthenticatedAskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmployeeRoute = AuthenticatedEmployeeRouteImport.update({
  id: '/employee',
  path: '/employee',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEnrollRoute = AuthenticatedEnrollRouteImport.update({
  id: '/enroll',
  path: '/enroll',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHelpRoute = AuthenticatedHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedParentRoute = AuthenticatedParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudentRoute = AuthenticatedStudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeacherRoute = AuthenticatedTeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAttendSessionIdRoute =
  AuthenticatedAttendSessionIdRouteImport.update({
    id: '/attend/$sessionId',
    path: '/attend/$sessionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthSsoCallbackRoute = AuthSsoCallbackRouteImport.update({
  id: '/sso/callback',
  path: '/sso/callback',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/mcp': typeof McpRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/status': typeof StatusRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/ask': typeof AuthenticatedAskRoute
  '/employee': typeof AuthenticatedEmployeeRoute
  '/enroll': typeof AuthenticatedEnrollRoute
  '/help': typeof AuthenticatedHelpRoute
  '/parent': typeof AuthenticatedParentRoute
  '/student': typeof AuthenticatedStudentRoute
  '/teacher': typeof AuthenticatedTeacherRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/attend/$sessionId': typeof AuthenticatedAttendSessionIdRoute
  '/auth/sso/callback': typeof AuthSsoCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/mcp': typeof McpRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/status': typeof StatusRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/ask': typeof AuthenticatedAskRoute
  '/employee': typeof AuthenticatedEmployeeRoute
  '/enroll': typeof AuthenticatedEnrollRoute
  '/help': typeof AuthenticatedHelpRoute
  '/parent': typeof AuthenticatedParentRoute
  '/student': typeof AuthenticatedStudentRoute
  '/teacher': typeof AuthenticatedTeacherRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/attend/$sessionId': typeof AuthenticatedAttendSessionIdRoute
  '/auth/sso/callback': typeof AuthSsoCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/mcp': typeof McpRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/status': typeof StatusRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/ask': typeof AuthenticatedAskRoute
  '/_authenticated/employee': typeof AuthenticatedEmployeeRoute
  '/_authenticated/enroll': typeof AuthenticatedEnrollRoute
  '/_authenticated/help': typeof AuthenticatedHelpRoute
  '/_authenticated/parent': typeof AuthenticatedParentRoute
  '/_authenticated/student': typeof AuthenticatedStudentRoute
  '/_authenticated/teacher': typeof AuthenticatedTeacherRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/attend/$sessionId': typeof AuthenticatedAttendSessionIdRoute
  '/auth/sso/callback': typeof AuthSsoCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/privacy'
    | '/reset-password'
    | '/status'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/ask'
    | '/employee'
    | '/enroll'
    | '/help'
    | '/parent'
    | '/student'
    | '/teacher'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/attend/$sessionId'
    | '/auth/sso/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/privacy'
    | '/reset-password'
    | '/status'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/ask'
    | '/employee'
    | '/enroll'
    | '/help'
    | '/parent'
    | '/student'
    | '/teacher'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/attend/$sessionId'
    | '/auth/sso/callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/mcp'
    | '/privacy'
    | '/reset-password'
    | '/status'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/admin'
    | '/_authenticated/ask'
    | '/_authenticated/employee'
    | '/_authenticated/enroll'
    | '/_authenticated/help'
    | '/_authenticated/parent'
    | '/_authenticated/student'
    | '/_authenticated/teacher'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/attend/$sessionId'
    | '/auth/sso/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  McpRoute: typeof McpRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  StatusRoute: typeof StatusRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ask': {
      id: '/_authenticated/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AuthenticatedAskRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employee': {
      id: '/_authenticated/employee'
      path: '/employee'
      fullPath: '/employee'
      preLoaderRoute: typeof AuthenticatedEmployeeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/enroll': {
      id: '/_authenticated/enroll'
      path: '/enroll'
      fullPath: '/enroll'
      preLoaderRoute: typeof AuthenticatedEnrollRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help': {
      id: '/_authenticated/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AuthenticatedHelpRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parent': {
      id: '/_authenticated/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof AuthenticatedParentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student': {
      id: '/_authenticated/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof AuthenticatedStudentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teacher': {
      id: '/_authenticated/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof AuthenticatedTeacherRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/attend/$sessionId': {
      id: '/_authenticated/attend/$sessionId'
      path: '/attend/$sessionId'
      fullPath: '/attend/$sessionId'
      preLoaderRoute: typeof AuthenticatedAttendSessionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/sso/callback': {
      id: '/auth/sso/callback'
      path: '/sso/callback'
      fullPath: '/auth/sso/callback'
      preLoaderRoute: typeof AuthSsoCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAskRoute: typeof AuthenticatedAskRoute
  AuthenticatedEmployeeRoute: typeof AuthenticatedEmployeeRoute
  AuthenticatedEnrollRoute: typeof AuthenticatedEnrollRoute
  AuthenticatedHelpRoute: typeof AuthenticatedHelpRoute
  AuthenticatedParentRoute: typeof AuthenticatedParentRoute
  AuthenticatedStudentRoute: typeof AuthenticatedStudentRoute
  AuthenticatedTeacherRoute: typeof AuthenticatedTeacherRoute
  AuthenticatedAttendSessionIdRoute: typeof AuthenticatedAttendSessionIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAskRoute: AuthenticatedAskRoute,
  AuthenticatedEmployeeRoute: AuthenticatedEmployeeRoute,
  AuthenticatedEnrollRoute: AuthenticatedEnrollRoute,
  AuthenticatedHelpRoute: AuthenticatedHelpRoute,
  AuthenticatedParentRoute: AuthenticatedParentRoute,
  AuthenticatedStudentRoute: AuthenticatedStudentRoute,
  AuthenticatedTeacherRoute: AuthenticatedTeacherRoute,
  AuthenticatedAttendSessionIdRoute: AuthenticatedAttendSessionIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthSsoCallbackRoute: typeof AuthSsoCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSsoCallbackRoute: AuthSsoCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  McpRoute: McpRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  StatusRoute: StatusRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
