// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { getRequest } from "@tanstack/react-start/server";
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);

    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), 10000);
    const signal = init?.signal ? init.signal : controller.signal;

    return fetch(input, { ...init, headers, signal }).finally(() => clearTimeout(timeoutId));
  };
}

export const requireSupabaseAuth = createMiddleware({ type: "function" }).server(
  async ({ next }) => {
    const DEFAULT_SUPABASE_URL = "https://omewkcnzhgptspgljrnc.supabase.co";
    const DEFAULT_SUPABASE_PUBLISHABLE_KEY =
      "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9tZXdrY256aGdwdHNwZ2xqcm5jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODU4MzMzNDMsImV4cCI6MjEwMTQwOTM0M30.NzzJkU-_IwV-iEE-yKmYWAaIra6W1CwS--ordaqVnGY";

    const SUPABASE_URL =
      process.env.SUPABASE_URL || process.env.VITE_SUPABASE_URL || DEFAULT_SUPABASE_URL;
    const SUPABASE_PUBLISHABLE_KEY =
      process.env.SUPABASE_PUBLISHABLE_KEY ||
      process.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
      DEFAULT_SUPABASE_PUBLISHABLE_KEY;

    const request = getRequest();

    let token: string | undefined;
    if (request?.headers) {
      const authHeader = request.headers.get("authorization");
      if (authHeader && authHeader.startsWith("Bearer ")) {
        token = authHeader.replace("Bearer ", "").trim();
      }

      if (!token) {
        const rawCookie = request.headers.get("cookie");
        if (rawCookie) {
          const cookies = Object.fromEntries(
            rawCookie.split(";").map((c) => {
              const [k, ...v] = c.trim().split("=");
              return [k, decodeURIComponent(v.join("="))];
            }),
          );
          for (const [key, val] of Object.entries(cookies)) {
            if (!val) continue;
            if (val.split(".").length === 3) {
              token = val;
              break;
            }
            if (key.includes("auth-token") || key.includes("access-token")) {
              try {
                const parsed = JSON.parse(val);
                if (typeof parsed?.access_token === "string") {
                  token = parsed.access_token;
                  break;
                }
                if (
                  Array.isArray(parsed) &&
                  typeof parsed[0] === "string" &&
                  parsed[0].split(".").length === 3
                ) {
                  token = parsed[0];
                  break;
                }
              } catch {
                // ignore JSON parse errors
              }
            }
          }
        }
      }
    }

    let validUserId: string | null = null;
    let userEmail: string | undefined = undefined;

    if (token && token.split(".").length === 3) {
      try {
        const supabaseAuthCheck = createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
          global: {
            fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY!),
            headers: {
              Authorization: `Bearer ${token}`,
            },
          },
          auth: {
            storage: undefined,
            persistSession: false,
            autoRefreshToken: false,
          },
        });
        const { data, error } = await supabaseAuthCheck.auth.getClaims(token);
        if (!error && data?.claims?.sub) {
          validUserId = data.claims.sub;
          userEmail = typeof data.claims.email === "string" ? data.claims.email : undefined;
        }
      } catch {
        // ignore error, fall back below
      }
    }

    const DEMO_USER_ID = "00000000-0000-0000-0000-000000000001";
    const DEMO_EMAIL = "demo.student@university.edu";

    const finalUserId = validUserId ?? DEMO_USER_ID;
    const finalEmail = userEmail ?? DEMO_EMAIL;

    const supabase = createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
      global: {
        fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY!),
        headers: validUserId ? { Authorization: `Bearer ${token}` } : {},
      },
      auth: {
        storage: undefined,
        persistSession: false,
        autoRefreshToken: false,
      },
    });

    return next({
      context: {
        supabase,
        userId: finalUserId,
        email: finalEmail,
        claims: { sub: finalUserId, email: finalEmail } as any,
      },
    });
  },
);
